### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Tori Scott",
  "email": "toriscott@example.com",
  "password": "bayside",
  "password_confirmation": "bayside"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "zackmorris@example.com",
  "password": "bayside"
}