@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo1LCJleHAiOjE2NTI1NTE5NDV9.tqKveC5D1zlCjXQj8dCZuxxNrIPmxV9LlxL2HrsRzek

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Amanda Hale",
  "email": "ahale@example.com",
  "password": "bayside",
  "password_confirmation": "bayside"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "screechpowers@example.com",
  "password": "bayside"
}

### Course create
POST http://localhost:3000/courses.json
Authorization: Bearer {{ jwt }}
Content-Type: application/json

{
  "name": "PreCalculus", 
  "grade": "B", 
  "credits": 0.5, 
  "level": "traditional", 
  "semester_taken": "11th Grade: Semester One", 
  "user_id": 5
}

### Course Index
GET http://localhost:3000/courses.json
Authorization: Bearer {{ jwt }}
Content-Type: application/json


### Course Show
GET http://localhost:3000/courses/60.json 
Authorization: Bearer {{ jwt }}
Content-Type: application/json

### Course Update

PATCH http://localhost:3000/courses/17.json
Authorization: Bearer {{ jwt }}
Content-Type: application/json

{
  "name": "Geometry", 
  "grade": "B+"
}

### Course Removal
DELETE http://localhost:3000/courses/17.json
Authorization: Bearer {{ jwt }}
Content-Type: application/json